apiVersion: v1
kind: Secret
metadata:
  name: artifactory-database-creds
  labels:
    app: artifactory
    chart: artifactory-107.38.10
    heritage: Helm
    release: artifactory
type: Opaque
data:
  db-url: "amRiYzpwb3N0Z3JlczovLzEwLjI2LjQ4LjM6NTQzMi9hcnRpZmFjdG9yeWs4cz9zc2xtb2RlPWRpc2FibGU="
  db-user: "cG9zdGdyZXM="
  db-password: "YzBuYW4xMDE="