apiVersion: v1
kind: Secret
metadata:
  name: artifactory-database-creds
  labels:
    app: artifactory
    chart: artifactory-107.39.4
    heritage: Helm
    release: artifactory
type: Opaque
data:
  db-url: "amRiYzpwb3N0Z3Jlc3FsOi8vbG9jYWxob3N0OjU0MzIvYXJ0aWZhY3RvcnlrOHM/c3NsbW9kZT1kaXNhYmxl"
  db-user: "cG9zdGdyZXM="
  db-password: "YzBuYW4xMDE="