apiVersion: v1
kind: Secret
metadata:
  name: artifactory
  labels:
    app: artifactory
    chart: artifactory-107.38.10
    heritage: Helm
    release: artifactory
type: Opaque
data:
  master-key: "MjQ2MDBmNTllNTNjODZjNDBkZGRjZWI0OWI5YzYxZmQ5NjFmMGVhNjI1OWM3NmRmYThhYTUzODlmNjJmYmE4Mw=="
  join-key: "ZWUwMjlkNjVhNDQwZmRhYzg3NTM1ZmZhZjQxYTI5NzBkNmYzNTEwY2RlMWZjNTNlZGY5NDFiZTU2MTM4ZGNmZQ=="