kind: Secret
apiVersion: v1
metadata:
  name: artifactory-binarystore
  labels:
    app: artifactory
    chart: artifactory-107.38.10
    heritage: Helm
    release: artifactory
stringData:
  binarystore.xml: |-