apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: artifactory-data-pvc
  labels:
    app: artifactory
    chart: artifactory-107.39.4
    heritage: Helm
    release: artifactory
    type: nfs-volume
spec:
  storageClassName: nfs-storageclass # SAME NAME AS THE STORAGECLASS
  accessModes:
    - ReadWriteMany #  must be the same as PersistentVolume
  resources:
    requests:
      storage: 4G