apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: artifactory-backup-pvc
spec:
  storageClassName: nfs-storageclass # SAME NAME AS THE STORAGECLASS
  accessModes:
    - ReadWriteMany #  must be the same as PersistentVolume
  resources:
    requests:
      storage: 1G
