apiVersion: v1
kind: Secret
metadata:
  name: artifactory-database-creds
  labels:
    app: artifactory
    chart: artifactory-107.38.10
    heritage: Helm
    release: artifactory
type: Opaque
data:
  db-url: "amRiYzpwb3N0Z3Jlc2w6Ly8xMC4yNi40OC4zOjU0MzIvYXJ0aWZhY3RvcnlrOHM/c3NsbW9kZT1kaXNhYmxl"
  db-user: "cG9zdGdyZXM="
  db-password: "YzBuYW4xMDE="