apiVersion: v1
kind: Service
metadata:
  name: distribution
  labels:
    app: distribution
    chart: distribution-102.13.4
    heritage: Helm
    release: distribution
    component: distribution
spec:
  type: ClusterIP
  ports:
    - name: http-distro
      port: 80
      targetPort: http-distro
  selector:
    app: distribution
    release: distribution
    component: distribution