apiVersion: v1
kind: Secret
metadata:
  name: distribution
  labels:
    app: distribution
    chart: distribution-102.13.4
    heritage: Helm
    release: distribution
type: Opaque
data:
  master-key: "QkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQg=="
  join-key: "NDk5NTFmZTcyOTkwYjgyZmI0OWY2MTJiYmE5ZWRiYzI3ZmM2NmZlZDZjMzY3OWY4OTU5MjM0ZDk3Mzk3ODNjZg=="
  redis-password: "TWhNZktCaXZZeA=="