apiVersion: v1
kind: Secret
metadata:
  name: artifactory
  labels:
    app: artifactory
    chart: artifactory-107.39.4
    heritage: Helm
    release: artifactory
type: Opaque
data:
  master-key: "Njc1YjZiNjYxY2NhNzM0MjY2ZWExMDEyMGEzZTY4NThiYmE3YmRlNWE5OWQxYTAzNmVlOTZkZmUwMzY3OTdlMw=="
  join-key: "NDk5NTFmZTcyOTkwYjgyZmI0OWY2MTJiYmE5ZWRiYzI3ZmM2NmZlZDZjMzY3OWY4OTU5MjM0ZDk3Mzk3ODNjZg=="