### Artifactory HA backup
apiVersion: v1
kind: PersistentVolume
metadata:
  name: artifactory-backup-pv
  labels:
    app: artifactory
    chart: artifactory-107.39.4
    heritage: Helm
    release: artifactory
    id: artifactory-backup-pv
    type: nfs-volume
spec:
  storageClassName: nfs-storageclass
  claimRef:
    name: artifactory-backup-pvc
    namespace: artifactory
  capacity:
    storage: 4Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.186.0.12
    path: "/var/nfsshare/rt-backup"
    readOnly: false