apiVersion: v1
kind: Secret
metadata:
  name: xray-system-yaml
  labels:
    app: xray
    chart: xray-103.52.4
    heritage: Helm
    release: xray
type: Opaque
stringData:
  system.yaml: |
    configVersion: 1
    router:
      serviceRegistry:
        insecure: false
    shared:
      logging:
        consoleLog:
          enabled: false
      jfrogUrl: "http://10.186.0.21"
      database:
        type: postgresql
        driver: org.postgresql.Driver