apiVersion: v1
kind: Secret
metadata:
  name: xray
  labels:
    app: xray
    chart: xray-103.52.4
    heritage: Helm
    release: xray
type: Opaque
data:
  master-key: "NTE4Y2Y0MWI1NTc3NWE2MzgxNThjZjlmMzIzZGVhZDM3YWQ5ZDU3NTc2NDgwZmI2ZDQxMmRmYzczMjVlOWVhNA=="
  join-key: "NDk5NTFmZTcyOTkwYjgyZmI0OWY2MTJiYmE5ZWRiYzI3ZmM2NmZlZDZjMzY3OWY4OTU5MjM0ZDk3Mzk3ODNjZg=="
  execution-service-aes-key: "b0FCWDNWVlQ2MFZ3akVSa1lZVXVxTDlHWG1tcWJFQUc="