apiVersion: v1
kind: ServiceAccount
metadata:
  name: xray-rabbitmq
  namespace: "xray"
  labels:
    app.kubernetes.io/name: rabbitmq
    helm.sh/chart: rabbitmq-8.31.6
    app.kubernetes.io/instance: xray
    app.kubernetes.io/managed-by: Helm
automountServiceAccountToken: true
secrets:
  - name: xray-rabbitmq