apiVersion: v1
kind: Service
metadata:
  name: xray
  labels:
    app: xray
    chart: xray-103.52.4
    component: xray
    heritage: Helm
    release: xray
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      name: http
      targetPort: 8000
    - port: 8082
      protocol: TCP
      name: http-router
      targetPort: 8082
  selector:
    app: xray
    component: xray
    release: xray