apiVersion: v1
kind: Secret
metadata:
  name: xray-rabbitmq
  namespace: "xray"
  labels:
    app.kubernetes.io/name: rabbitmq
    helm.sh/chart: rabbitmq-8.31.6
    app.kubernetes.io/instance: xray
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  rabbitmq-password: "dkhNamhJRENpTw=="
  rabbitmq-erlang-cookie: "WFJBWVJBQkJJVE1RQ0xVU1RFUg=="