kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: xray-rabbitmq-endpoint-reader
  namespace: "xray"
  labels:
    app.kubernetes.io/name: rabbitmq
    helm.sh/chart: rabbitmq-8.31.6
    app.kubernetes.io/instance: xray
    app.kubernetes.io/managed-by: Helm
rules:
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create"]